spring.application.name=webcomparasalud
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/db_comparasalud
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Configuración de Logs en consola y archivo
logging.level.root=INFO
logging.level.com.upc.webcomparasalud=info
logging.file.name=logs/api.log
#Evitando
spring.web.error.include-stacktrace=never
#Seguridad
ip.frontend=http://localhost:4200
jwt.secret=rZxQB1RDsrS9HPqqgLfiB0JbviuA4zwDZnASOYWJA8qaaeL49rtNS/hRVrQridpb7mVPVXFVNnhnbk5ayDyFlA==
